// <auto-generated />
using System;
using ChatApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChatApp.Api.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20260202212300_SesliMesajAltyapisi")]
    partial class SesliMesajAltyapisi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatApp.Api.Entities.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SonGorulme")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("ChatApp.Api.Entities.Mesaj", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AliciId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GonderenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GonderilmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MesajTuru")
                        .HasColumnType("integer");

                    b.Property<string>("SifreliIcerikAlici")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SifreliIcerikGonderen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SunucuAlisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Mesajlar");
                });
#pragma warning restore 612, 618
        }
    }
}
